### ISSUE TITLE
Nem megírt dolgozat 0-nak számít az átlagszámolásnál

### ISSUE THREAD

**Issue by coolbreon** [LovassyApp/LovassyApp#10]
**Írd körül a hibát**
A Jegyeknél ha tantárgyat választunk ki, az átlag hibásan van kiszámolva abban az esetben, amikor a tanulónak van 'Nem írt' dolgozat a naplóban

**Comment by Xeretis** [comment]
Javítva a ff5320b0588e02020a18a04c6d9896e07bf6ffaf commitban. A jelenlegi élő változat ezt tartalmazza.
